apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pong-game-preferences-data
  labels:
    app: pong-game
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
