apiVersion: v1
kind: Service
metadata:
  name: pong-game
  labels:
    app: pong-game
spec:
  type: LoadBalancer
  selector:
    app: pong-game
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
