#!/bin/sh
# deploy.sh – Build and deploy the Pong game to Fly.io
#
# Environment variables (provided by Mendel):
#   FLY_API_TOKEN       – Fly.io personal access token
#   MENDEL_VARIATION_ID – Unique identifier for this variation/deployment
#
# Runs inside an alpine:latest deployer container with the repository
# mounted at /workspace.  Prints ONLY the deployed URL to stdout on success.

set -eu

# ── Install flyctl ─────────────────────────────────────────────────────────────
if ! command -v flyctl >/dev/null 2>&1; then
  echo "Installing flyctl..." >&2
  # Ensure curl is available (alpine may not have it)
  if ! command -v curl >/dev/null 2>&1; then
    apk add --no-cache curl >&2
  fi
  curl -fsSL https://fly.io/install.sh | sh >&2
fi

# Make sure flyctl is on PATH whether it was just installed or pre-existing
export PATH="${HOME}/.fly/bin:${PATH}"

if ! command -v flyctl >/dev/null 2>&1; then
  echo "ERROR: flyctl installation failed." >&2
  exit 1
fi
echo "flyctl version: $(flyctl version 2>&1 | head -1)" >&2

# ── Validate required environment variables ───────────────────────────────────
if [ -z "${FLY_API_TOKEN:-}" ]; then
  echo "ERROR: FLY_API_TOKEN is not set." >&2
  exit 1
fi

if [ -z "${MENDEL_VARIATION_ID:-}" ]; then
  echo "ERROR: MENDEL_VARIATION_ID is not set." >&2
  exit 1
fi

export FLY_API_TOKEN

# ── Derive a Fly.io-compatible app name ───────────────────────────────────────
# Rules: lowercase letters, digits, hyphens only; max 30 chars total.
SHORT_ID=$(printf '%s' "${MENDEL_VARIATION_ID}" \
  | tr '[:upper:]' '[:lower:]' \
  | tr -cs 'a-z0-9' '-' \
  | sed 's/^-*//;s/-*$//' \
  | cut -c1-20)
APP_NAME="pong-${SHORT_ID}"
echo "Fly.io app name: ${APP_NAME}" >&2

# ── Locate workspace root ─────────────────────────────────────────────────────
if [ -d "/workspace" ]; then
  REPO_ROOT="/workspace"
else
  REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi
echo "Repository root: ${REPO_ROOT}" >&2
cd "${REPO_ROOT}"

# ── Create the Fly app if it does not already exist ──────────────────────────
APP_EXISTS=$(flyctl apps list --json 2>/dev/null \
  | grep '"Name"' \
  | grep "\"${APP_NAME}\"" || true)

if [ -n "${APP_EXISTS}" ]; then
  echo "App '${APP_NAME}' already exists – redeploying." >&2
else
  echo "Creating Fly.io app '${APP_NAME}'..." >&2
  if ! flyctl apps create "${APP_NAME}" --machines >&2 2>&1; then
    # Re-check in case of a race condition from a parallel run
    APP_EXISTS=$(flyctl apps list --json 2>/dev/null \
      | grep '"Name"' \
      | grep "\"${APP_NAME}\"" || true)
    if [ -z "${APP_EXISTS}" ]; then
      echo "ERROR: Failed to create Fly.io app '${APP_NAME}'." >&2
      exit 1
    fi
    echo "App already existed (race condition – continuing)." >&2
  fi
fi

# ── Write fly.toml ─────────────────────────────────────────────────────────────
FLY_TOML="${REPO_ROOT}/fly.toml"
echo "Writing ${FLY_TOML}..." >&2

cat > "${FLY_TOML}" << TOML
# Auto-generated by Mendel deploy.sh – do not edit manually.
app            = "${APP_NAME}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port        = 3000
  force_https          = true
  auto_stop_machines   = true
  auto_start_machines  = true
  min_machines_running = 0

  [http_service.concurrency]
    type       = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory   = "256mb"
  cpu_kind = "shared"
  cpus     = 1
TOML

# ── Deploy ────────────────────────────────────────────────────────────────────
echo "Deploying '${APP_NAME}' to Fly.io (this may take a few minutes)..." >&2
if ! flyctl deploy \
    --app        "${APP_NAME}" \
    --config     "${FLY_TOML}" \
    --dockerfile "${REPO_ROOT}/Dockerfile" \
    --remote-only \
    --yes \
    >&2; then
  echo "ERROR: flyctl deploy failed for app '${APP_NAME}'." >&2
  exit 1
fi

# ── Retrieve the public hostname ──────────────────────────────────────────────
# Fly.io always exposes apps at <app-name>.fly.dev; the JSON confirms it.
HOSTNAME=$(flyctl info --app "${APP_NAME}" --json 2>/dev/null \
  | grep '"Hostname"' \
  | head -n1 \
  | sed 's/.*"Hostname"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' || true)

if [ -z "${HOSTNAME}" ]; then
  # Fallback: the default Fly.io subdomain is always predictable
  HOSTNAME="${APP_NAME}.fly.dev"
fi

echo "Deployment complete. App is live at https://${HOSTNAME}" >&2

# ── CRITICAL: print ONLY the URL to stdout so Mendel can capture it ──────────
echo "https://${HOSTNAME}"
