#!/bin/sh
# deploy.sh – Build and deploy the Pong game to Fly.io
#
# Environment variables (provided by Mendel):
#   FLY_API_TOKEN       – Fly.io personal access token
#   MENDEL_VARIATION_ID – Unique identifier for this variation/deployment
#
# Runs inside an alpine:latest deployer container with the repository
# mounted at /workspace.  Prints ONLY the deployed URL to stdout.

set -eu

# ── Install flyctl (not present in alpine base image) ────────────────────────
if ! command -v flyctl >/dev/null 2>&1; then
  echo "Installing flyctl..." >&2
  # apk provides curl; fall back to wget if curl is absent
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL https://fly.io/install.sh | sh >&2
  else
    apk add --no-cache curl >&2
    curl -fsSL https://fly.io/install.sh | sh >&2
  fi
  export PATH="$HOME/.fly/bin:$PATH"
fi

# Ensure flyctl is on PATH even if it was already installed
export PATH="$HOME/.fly/bin:$PATH"

if ! command -v flyctl >/dev/null 2>&1; then
  echo "ERROR: flyctl installation failed." >&2
  exit 1
fi

# ── Validate required environment variables ───────────────────────────────────
if [ -z "${FLY_API_TOKEN:-}" ]; then
  echo "ERROR: FLY_API_TOKEN is not set." >&2
  exit 1
fi

if [ -z "${MENDEL_VARIATION_ID:-}" ]; then
  echo "ERROR: MENDEL_VARIATION_ID is not set." >&2
  exit 1
fi

export FLY_API_TOKEN

# ── Derive a stable, Fly.io-compatible app name ───────────────────────────────
# Fly.io rules: lowercase letters, digits, hyphens only; max 30 chars.
SHORT_ID=$(printf '%s' "${MENDEL_VARIATION_ID}" \
  | tr '[:upper:]' '[:lower:]' \
  | tr -cs 'a-z0-9' '-' \
  | sed 's/^-//;s/-$//' \
  | cut -c1-20)
APP_NAME="pong-${SHORT_ID}"

echo "Fly.io app name: ${APP_NAME}" >&2

# ── Locate workspace root ─────────────────────────────────────────────────────
if [ -d "/workspace" ]; then
  REPO_ROOT="/workspace"
else
  REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi
echo "Repository root: ${REPO_ROOT}" >&2
cd "${REPO_ROOT}"

# ── Create the Fly app if it does not already exist ──────────────────────────
if flyctl apps list --json 2>/dev/null | grep -q "\"${APP_NAME}\""; then
  echo "App '${APP_NAME}' already exists – redeploying." >&2
else
  echo "Creating Fly.io app '${APP_NAME}'..." >&2
  if ! flyctl apps create "${APP_NAME}" --machines >&2; then
    # Check again in case of a race with a previous run
    if ! flyctl apps list --json 2>/dev/null | grep -q "\"${APP_NAME}\""; then
      echo "ERROR: Failed to create Fly.io app '${APP_NAME}'." >&2
      exit 1
    fi
    echo "App already existed (race condition – continuing)." >&2
  fi
fi

# ── Write a fly.toml tailored for this deployment ────────────────────────────
FLY_TOML="${REPO_ROOT}/fly.toml"
echo "Writing ${FLY_TOML}..." >&2

cat > "${FLY_TOML}" << TOML
# Auto-generated by Mendel deploy.sh – do not edit manually.
app            = "${APP_NAME}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port        = 3000
  force_https          = true
  auto_stop_machines   = true
  auto_start_machines  = true
  min_machines_running = 0

  [http_service.concurrency]
    type       = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory   = "256mb"
  cpu_kind = "shared"
  cpus     = 1
TOML

# ── Deploy the application ────────────────────────────────────────────────────
echo "Deploying '${APP_NAME}' to Fly.io..." >&2
if ! flyctl deploy \
    --app        "${APP_NAME}" \
    --config     "${FLY_TOML}" \
    --dockerfile "${REPO_ROOT}/Dockerfile" \
    --remote-only \
    --yes \
    >&2; then
  echo "ERROR: flyctl deploy failed for app '${APP_NAME}'." >&2
  exit 1
fi

# ── Retrieve the public hostname ──────────────────────────────────────────────
HOSTNAME=$(flyctl info --app "${APP_NAME}" --json 2>/dev/null \
  | grep '"Hostname"' \
  | head -n1 \
  | sed 's/.*"Hostname": *"\([^"]*\)".*/\1/')

# Fly.io always provides <app-name>.fly.dev as the default hostname
if [ -z "${HOSTNAME}" ]; then
  HOSTNAME="${APP_NAME}.fly.dev"
fi

# ── CRITICAL: print ONLY the URL to stdout so Mendel can capture it ──────────
echo "https://${HOSTNAME}"
