#!/usr/bin/env sh
# deploy.sh – Deploy the Pong game to Fly.io
# Required env vars:
#   FLY_API_TOKEN       – Fly.io API token
#   MENDEL_VARIATION_ID – Unique ID injected by Mendel for resource naming
set -eu

# ── Validation ────────────────────────────────────────────────────────────────
if [ -z "${FLY_API_TOKEN:-}" ]; then
  echo "ERROR: FLY_API_TOKEN is not set." >&2
  exit 1
fi

if [ -z "${MENDEL_VARIATION_ID:-}" ]; then
  echo "ERROR: MENDEL_VARIATION_ID is not set." >&2
  exit 1
fi

export FLY_API_TOKEN

# ── App name (max 30 chars, Fly.io requirement) ───────────────────────────────
# Truncate MENDEL_VARIATION_ID so the full name stays within limits.
SHORT_ID=$(echo "${MENDEL_VARIATION_ID}" | tr '[:upper:]' '[:lower:]' | tr '_' '-' | cut -c1-20)
APP_NAME="pong-${SHORT_ID}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── Ensure flyctl is available ────────────────────────────────────────────────
if ! command -v flyctl >/dev/null 2>&1; then
  echo "ERROR: flyctl is not installed or not in PATH." >&2
  exit 1
fi

# ── Create the Fly app if it doesn't already exist ───────────────────────────
if flyctl apps list --json 2>/dev/null | grep -q "\"${APP_NAME}\""; then
  echo "App '${APP_NAME}' already exists – reusing." >&2
else
  echo "Creating Fly.io app '${APP_NAME}'..." >&2
  flyctl apps create "${APP_NAME}" --machines 2>/dev/null || {
    # Tolerate "already exists" races
    if ! flyctl apps list --json 2>/dev/null | grep -q "\"${APP_NAME}\""; then
      echo "ERROR: Failed to create Fly.io app '${APP_NAME}'." >&2
      exit 1
    fi
  }
fi

# ── Write a minimal fly.toml for this deployment ─────────────────────────────
DEPLOY_DIR="${REPO_ROOT}"
FLY_TOML="${DEPLOY_DIR}/fly.toml"

cat > "${FLY_TOML}" <<TOML
# Auto-generated by Mendel deploy.sh – do not edit by hand.
app = "${APP_NAME}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https   = true
  auto_stop_machines  = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type       = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
TOML

# ── Deploy ────────────────────────────────────────────────────────────────────
echo "Deploying '${APP_NAME}' to Fly.io..." >&2
flyctl deploy \
  --app "${APP_NAME}" \
  --config "${FLY_TOML}" \
  --dockerfile "${DEPLOY_DIR}/Dockerfile" \
  --remote-only \
  --yes \
  2>&1 | grep -v "^#" >&2 || {
  echo "ERROR: flyctl deploy failed." >&2
  exit 1
}

# ── Retrieve the hostname and emit the URL to stdout ─────────────────────────
HOSTNAME=$(flyctl info --app "${APP_NAME}" --json 2>/dev/null \
  | grep '"Hostname"' \
  | head -n1 \
  | sed 's/.*"Hostname": *"\([^"]*\)".*/\1/')

if [ -z "${HOSTNAME}" ]; then
  # Fallback: Fly.io always assigns <app>.fly.dev
  HOSTNAME="${APP_NAME}.fly.dev"
fi

# CRITICAL: print only the URL to stdout so Mendel can capture it.
echo "https://${HOSTNAME}"
