#!/usr/bin/env sh
# deploy.sh – Build and deploy the Pong game to Fly.io
#
# Environment variables (provided by Mendel):
#   FLY_API_TOKEN       – Fly.io personal access token
#   MENDEL_VARIATION_ID – Unique identifier for this variation/deployment
#
# The script is executed inside the flyio/flyctl container image with the
# repository mounted at /workspace.  It must print ONLY the deployed URL
# to stdout so Mendel can capture it.

set -eu

# ── Validate required environment variables ───────────────────────────────────
if [ -z "${FLY_API_TOKEN:-}" ]; then
  echo "ERROR: FLY_API_TOKEN is not set." >&2
  exit 1
fi

if [ -z "${MENDEL_VARIATION_ID:-}" ]; then
  echo "ERROR: MENDEL_VARIATION_ID is not set." >&2
  exit 1
fi

export FLY_API_TOKEN

# ── Derive a stable, Fly.io-compatible app name ───────────────────────────────
# Fly.io requires: lowercase letters, digits, hyphens; max 30 chars.
SHORT_ID=$(printf '%s' "${MENDEL_VARIATION_ID}" \
  | tr '[:upper:]' '[:lower:]' \
  | tr -cs 'a-z0-9' '-' \
  | sed 's/^-//;s/-$//' \
  | cut -c1-20)
APP_NAME="pong-${SHORT_ID}"

echo "Using Fly.io app name: ${APP_NAME}" >&2

# ── Locate the workspace root (/workspace is mounted by Mendel) ───────────────
if [ -d "/workspace" ]; then
  REPO_ROOT="/workspace"
else
  # Fallback: derive from script location
  REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi

echo "Repository root: ${REPO_ROOT}" >&2

# ── Verify flyctl is available ────────────────────────────────────────────────
if ! command -v flyctl >/dev/null 2>&1; then
  echo "ERROR: flyctl not found in PATH." >&2
  exit 1
fi

# ── Create the Fly app if it does not already exist ──────────────────────────
EXISTING=$(flyctl apps list --json 2>/dev/null || echo '[]')
if printf '%s' "${EXISTING}" | grep -q "\"${APP_NAME}\""; then
  echo "App '${APP_NAME}' already exists – redeploying." >&2
else
  echo "Creating Fly.io app '${APP_NAME}'..." >&2
  flyctl apps create "${APP_NAME}" --machines >&2 || {
    # Re-check in case of a race with a previous run
    EXISTING=$(flyctl apps list --json 2>/dev/null || echo '[]')
    if ! printf '%s' "${EXISTING}" | grep -q "\"${APP_NAME}\""; then
      echo "ERROR: Failed to create Fly.io app '${APP_NAME}'." >&2
      exit 1
    fi
    echo "App already existed (race condition – continuing)." >&2
  }
fi

# ── Write a fly.toml tailored for this deployment ────────────────────────────
FLY_TOML="${REPO_ROOT}/fly.toml"
echo "Writing ${FLY_TOML}..." >&2

cat > "${FLY_TOML}" << TOML
# Auto-generated by Mendel deploy.sh – do not edit manually.
app            = "${APP_NAME}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port        = 3000
  force_https          = true
  auto_stop_machines   = true
  auto_start_machines  = true
  min_machines_running = 0

  [http_service.concurrency]
    type       = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory   = "256mb"
  cpu_kind = "shared"
  cpus     = 1
TOML

# ── Deploy the application ────────────────────────────────────────────────────
echo "Deploying '${APP_NAME}' to Fly.io..." >&2
flyctl deploy \
  --app        "${APP_NAME}" \
  --config     "${FLY_TOML}" \
  --dockerfile "${REPO_ROOT}/Dockerfile" \
  --remote-only \
  --yes \
  >&2 || {
  echo "ERROR: flyctl deploy failed for app '${APP_NAME}'." >&2
  exit 1
}

# ── Retrieve the public hostname ──────────────────────────────────────────────
HOSTNAME=$(flyctl info --app "${APP_NAME}" --json 2>/dev/null \
  | grep '"Hostname"' \
  | head -n1 \
  | sed 's/.*"Hostname": *"\([^"]*\)".*/\1/')

# Fly.io always provides <app-name>.fly.dev even if the JSON parse fails
if [ -z "${HOSTNAME}" ]; then
  HOSTNAME="${APP_NAME}.fly.dev"
fi

# ── CRITICAL: print only the URL to stdout for Mendel to capture ─────────────
echo "https://${HOSTNAME}"
